apiVersion: v1
kind: Secret
metadata:
  name: petclinic-db-secret
type: Opaque
stringData:
  # Customers Service DB credentials
  CUSTOMERS_DATASOURCE_USERNAME: <YOUR_CUSTOMERS_DB_USERNAME>
  CUSTOMERS_DATASOURCE_PASSWORD: <YOUR_CUSTOMERS_DB_PASSWORD>
  # Vets Service DB credentials
  VETS_DATASOURCE_USERNAME: <YOUR_VETS_DB_USERNAME>
  VETS_DATASOURCE_PASSWORD: <YOUR_VETS_DB_PASSWORD>
  # Visits Service DB credentials
  VISITS_DATASOURCE_USERNAME: <YOUR_VISITS_DB_USERNAME>
  VISITS_DATASOURCE_PASSWORD: <YOUR_VISITS_DB_PASSWORD>

