apiVersion: v1
kind: Secret
metadata:
  name: petclinic-db-secret
type: Opaque
stringData:
  # Customers Service DB credentials
  CUSTOMERS_DATASOURCE_USERNAME: customers_user
  CUSTOMERS_DATASOURCE_PASSWORD: your_customers_password
  # Vets Service DB credentials
  VETS_DATASOURCE_USERNAME: vets_user
  VETS_DATASOURCE_PASSWORD: your_vets_password
  # Visits Service DB credentials
  VISITS_DATASOURCE_USERNAME: visits_user
  VISITS_DATASOURCE_PASSWORD: your_visits_password

